"""updated user model - added phone number

Revision ID: 61ed2a292aed
Revises: 9d0ffd291843
Create Date: 2023-12-01 16:30:55.275918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61ed2a292aed'
down_revision: Union[str, None] = '9d0ffd291843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phonenumber', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'users', ['phonenumber'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'phonenumber')
    # ### end Alembic commands ###
