"""changing products in profile to list try

Revision ID: eb83bf2a70e7
Revises: 5455a14f92e2
Create Date: 2024-06-05 20:37:10.595420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb83bf2a70e7'
down_revision: Union[str, None] = '5455a14f92e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
