"""changing products in profile to list try changes

Revision ID: f883d6d9b1a9
Revises: eb83bf2a70e7
Create Date: 2024-06-05 20:39:33.643063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f883d6d9b1a9'
down_revision: Union[str, None] = 'eb83bf2a70e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
